---
name: tests
on: [ push, pull_request ]
jobs:
  test:
    name: Test (Ruby ${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1', '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Test
        run: ruby test/aspect_ratio_test.rb
